### PR TITLE
adding posibility to remove whitespace before closing tag in reformat...

### PR DESCRIPTION
**Pull request by seavan**
…ted jsx elements.

This makes it possible to format JSX similarly to WebStorm, which is important for my team :) Take a look, maybe you can make it in some more direct way, though.

### CODE REVIEW

**Comment by royriojas** [comment]
Hi @seavan very nice! 

Can you please add some unit tests? Will be more than happy to merge it. 

Regards

**Comment by seavan** [comment]
Done :)

**Comment by royriojas** [comment]
Thank you very much for the tests.

One last thing to proceed to merge, can you please update the readme with the description and default value of the flag you added.

It doesn't need to be a big description, as the name is descriptive enough I believe, but at least for people to be aware the flag is there.

**Comment by seavan** [comment]
added!

**Comment by royriojas** [comment]
Published in `v5.0.2` @seavan Thank you!

**Pull request merged**
