### PR TITLE
Replace string like placeholder with variable

### PR DESCRIPTION
**Pull request by webcarrot**
See issue: https://github.com/millermedeiros/esformatter-quotes/issues/16

### CODE REVIEW

**Comment by dacarley** [comment]
This is a pretty nasty bug -- we've had to remove esformatter-jsx from our project entirely until this gets fixed.

**Comment by royriojas** [comment]
Sorry @webcarrot @dacarley, 

This issue was really a nasty one, but just to confirm was the issue also happening if `esformatter-jsx` was the first plugin in the list of esformatter plugins?

**Comment by dacarley** [comment]
Yes -- `esformatter-jsx` was the first plugin listed in our config.

**Comment by royriojas** [comment]
esformatter-jsx@7.0.1 published

**Comment by royriojas** [comment]
I need to start adding tests that consider interaction with other plugins... It is really sad not being able to reproduce this issue in a unit test. It might comeback later :(

**Pull request merged**
