### PR TITLE
Fixed decorators formatting bug #74

### PR DESCRIPTION
**Pull request by theadriann**
Issue: https://github.com/royriojas/esformatter-jsx/issues/74

### CODE REVIEW

**Comment by royriojas** [comment]
hi @theadriann 

Thank you very much for your contribution, will it be too much to ask to add unit tests for this one? please check the other unit tests that are there. 

I plan to move to use snapshots instead of what currently is there, sadly I haven't find time yet to fix this.

**Comment by theadriann** [comment]
Sure 📦 🚢

**Comment by theadriann** [comment]
@royriojas  is everything ok?

**Comment by royriojas** [comment]
it is sorry for the long delay to reply. It is merged now. Will publish a new version soon

**Comment by royriojas** [comment]
@theadriann published as `esformatter-jsx@8.0.1` 

Thank you very much on helping with the bug

**Pull request merged**
